"""empty message

Revision ID: a5ff0c20e028
Revises: 
Create Date: 2018-08-01 09:36:05.864338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ff0c20e028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('home_address', sa.String(length=120), nullable=True),
    sa.Column('home_city', sa.String(length=120), nullable=True),
    sa.Column('home_state', sa.String(length=2), nullable=True),
    sa.Column('work_address', sa.String(length=120), nullable=True),
    sa.Column('work_city', sa.String(length=120), nullable=True),
    sa.Column('work_state', sa.String(length=2), nullable=True),
    sa.Column('gender_preferred', sa.String(length=20), nullable=True),
    sa.Column('signup_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_gender'), 'user', ['gender'], unique=False)
    op.create_index(op.f('ix_user_gender_preferred'), 'user', ['gender_preferred'], unique=False)
    op.create_index(op.f('ix_user_home_address'), 'user', ['home_address'], unique=False)
    op.create_index(op.f('ix_user_home_city'), 'user', ['home_city'], unique=False)
    op.create_index(op.f('ix_user_home_state'), 'user', ['home_state'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_signup_status'), 'user', ['signup_status'], unique=False)
    op.create_index(op.f('ix_user_work_address'), 'user', ['work_address'], unique=False)
    op.create_index(op.f('ix_user_work_city'), 'user', ['work_city'], unique=False)
    op.create_index(op.f('ix_user_work_state'), 'user', ['work_state'], unique=False)
    op.create_table('car',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=True),
    sa.Column('mpg', sa.Float(), nullable=True),
    sa.Column('manufacturer', sa.String(length=60), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('license_plate_num', sa.String(length=7), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('license_plate_num')
    )
    op.create_index(op.f('ix_car_num_seats'), 'car', ['num_seats'], unique=False)
    op.create_table('daily_status',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_daily_status_status'), 'daily_status', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_status_status'), table_name='daily_status')
    op.drop_table('daily_status')
    op.drop_index(op.f('ix_car_num_seats'), table_name='car')
    op.drop_table('car')
    op.drop_index(op.f('ix_user_work_state'), table_name='user')
    op.drop_index(op.f('ix_user_work_city'), table_name='user')
    op.drop_index(op.f('ix_user_work_address'), table_name='user')
    op.drop_index(op.f('ix_user_signup_status'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_home_state'), table_name='user')
    op.drop_index(op.f('ix_user_home_city'), table_name='user')
    op.drop_index(op.f('ix_user_home_address'), table_name='user')
    op.drop_index(op.f('ix_user_gender_preferred'), table_name='user')
    op.drop_index(op.f('ix_user_gender'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
